[theme]
primaryColor = "#0D6EFD"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1A1F2C"
textColor = "#FAFAFA"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[client]
toolbarMode = "viewer"
